services:
  web:
    build: .
    ports:
      - "7223:7223"  # Проброс порта 8080 контейнера на 7223 хоста
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=MessageServiceDB;Username=postgres;Password=yourpassword
    networks:
      - app-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: MessageServiceDB
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
